baseURL = "https://morris-frank.dev"
title = "Morris-Frank"
publishDir = "docs"
assetDir = "layout"
layoutDir = "layout"

[permalinks]
posts = "/:filename/"

[taxonomies]
    tags = "tags"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[imaging]
  quality = 90
  resampleFilter = "lanczos"

[params]
  motionstills = "https://motionstill.morris-frank.dev/file/motionstills/"