name: Build with Hugo

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install hugo
        run: brew install hugo
      - name: Run hugo
        run: hugo -d docs --cleanDestinationDir
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build with hugp
